# Generated by Django 3.2.16 on 2022-11-03 16:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import journal.models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='APC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fixed_amount', models.CharField(max_length=100000)),
                ('discount_options', models.CharField(max_length=2)),
                ('waive_off', models.CharField(max_length=10000)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ArticleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('article_type', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('issue', models.IntegerField()),
                ('open_date', models.DateField(blank=True, null=True)),
                ('close_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'open'), ('close', 'close')], max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JournalMatrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submission_count', models.IntegerField()),
                ('publication_count', models.IntegerField()),
                ('rejected_count', models.IntegerField()),
                ('withdrawl_count', models.IntegerField()),
                ('citation_count', models.IntegerField()),
                ('h_5', models.IntegerField()),
                ('h_index', models.IntegerField()),
                ('download', models.CharField(max_length=1000)),
                ('views', models.CharField(max_length=1000)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PageNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_from', models.CharField(max_length=100000)),
                ('page_to', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='ScopeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scope_type', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Volume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('volume', models.IntegerField()),
                ('year', models.IntegerField(choices=[(1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022)], default=journal.models.Volume.current_year, verbose_name='year')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Journals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('journal_title', models.CharField(max_length=200, unique=True)),
                ('journal_slug', models.SlugField(max_length=200)),
                ('journal_image', models.ImageField(upload_to='journal-image')),
                ('is_lock', models.BooleanField(default=False)),
                ('description', tinymce.models.HTMLField()),
                ('scope', models.CharField(blank=True, max_length=200, null=True)),
                ('ISSN_PRINT', models.CharField(blank=True, max_length=50, null=True)),
                ('ISSN_ONLINE', models.CharField(blank=True, max_length=50, null=True)),
                ('DOI', models.URLField(max_length=1000)),
                ('frequency', models.CharField(choices=[('monthly', 'monthly'), ('bimonthly', 'bimonthly'), ('quaterly', 'quaterly'), ('half_yearly', 'half_yearly'), ('yearly', 'yearly')], default='monthly', max_length=100)),
                ('publication_year', models.IntegerField(choices=[(1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022)], default=journal.models.Journals.current_year, verbose_name='publication_year')),
                ('special_issue', models.CharField(blank=True, max_length=2000, null=True)),
                ('article_type', models.ManyToManyField(blank=True, null=True, to='journal.ArticleType')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriber_issue', to='journal.issue')),
                ('journal_author', models.ForeignKey(blank=True, limit_choices_to={'role__name': 'Author'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscriber_author_journal', to=settings.AUTH_USER_MODEL)),
                ('journal_matrix', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='journal_matrix', to='journal.journalmatrix')),
                ('journal_reviewer', models.ForeignKey(blank=True, limit_choices_to={'role__name': 'Reviewer'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscriber_reviewer_journal', to=settings.AUTH_USER_MODEL)),
                ('journal_subscriber', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscriber_journal', to=settings.AUTH_USER_MODEL)),
                ('volume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriber_volume', to='journal.volume')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
