# Generated by Django 4.0.2 on 2022-03-29 19:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import journal.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='APC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fixed_amount', models.CharField(max_length=100000)),
                ('discount_options', models.CharField(max_length=2)),
                ('waive_off', models.CharField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue', models.IntegerField()),
                ('open_date', models.DateField(blank=True, null=True)),
                ('close_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='JournalMatrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_count', models.IntegerField()),
                ('publication_count', models.IntegerField()),
                ('rejected_coount', models.IntegerField()),
                ('withdrawl_coount', models.IntegerField()),
                ('citation_coount', models.IntegerField()),
                ('h_5', models.IntegerField()),
                ('h_index', models.IntegerField()),
                ('download', models.CharField(max_length=1000)),
                ('views', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Volume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.IntegerField()),
                ('open_year', models.IntegerField(choices=[(1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022)], default=journal.models.Volume.current_year, verbose_name='year')),
                ('close_year', models.IntegerField(choices=[(1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022)], default=journal.models.Volume.current_year, verbose_name='year')),
            ],
        ),
        migrations.CreateModel(
            name='Journals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journal_id', models.IntegerField(blank=True, null=True)),
                ('journal_title', models.CharField(max_length=200, unique=True)),
                ('journal_image', models.ImageField(upload_to='journal-image')),
                ('description', models.TextField()),
                ('scope', models.CharField(choices=[('author', 'author'), ('editor', 'editor'), ('reviewer', 'reviewer'), ('article_processing_charge', 'article_processing_charge')], max_length=100)),
                ('article_type', models.CharField(choices=[('book_review', 'book_review'), ('clinical_case_study', 'clinical_case_study'), ('clinical_trial', 'clinical_trial'), ('dissertation_report', 'dissertation_report'), ('letters', 'letters'), ('opnion', 'opnion'), ('research_article', 'research_article'), ('review_article', 'review_article'), ('survey_report', 'survey_report'), ('conference_report', 'conference_report')], max_length=100)),
                ('ISSM_PRINT', models.IntegerField()),
                ('ISSM_ONLINE', models.IntegerField()),
                ('DOI', models.CharField(max_length=1000)),
                ('frequency', models.CharField(choices=[('monthly', 'monthly'), ('bimonthly', 'bimonthly'), ('quaterly', 'quaterly'), ('half_yearly', 'half_yearly'), ('yearly', 'yearly')], max_length=100)),
                ('publication_year', models.CharField(max_length=4)),
                ('special_issue', models.CharField(max_length=2000)),
                ('journal_matrix', models.CharField(max_length=100)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.issue')),
                ('journal_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_journal', to=settings.AUTH_USER_MODEL)),
                ('journal_reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewer_journal', to=settings.AUTH_USER_MODEL)),
                ('journal_subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriber_journal', to=settings.AUTH_USER_MODEL)),
                ('volume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.volume')),
            ],
        ),
    ]
