# Generated by Django 3.2.15 on 2022-11-01 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journals',
            name='scope',
        ),
        migrations.AddField(
            model_name='journals',
            name='scope',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
