# Generated by Django 4.0.2 on 2022-04-22 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='scope',
            new_name='journal',
        ),
        migrations.AddField(
            model_name='article',
            name='refrence',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='journals',
            name='is_lock',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='journals',
            name='journal_matrix',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='journal_matrix', to='journal.journalmatrix'),
        ),
    ]
