# Generated by Django 4.0.2 on 2022-03-30 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journalmatrix',
            old_name='citation_coount',
            new_name='citation_count',
        ),
        migrations.RenameField(
            model_name='journalmatrix',
            old_name='rejected_coount',
            new_name='rejected_count',
        ),
        migrations.RenameField(
            model_name='journalmatrix',
            old_name='withdrawl_coount',
            new_name='withdrawl_count',
        ),
    ]
