# Generated by Django 4.0.2 on 2022-04-02 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_rename_citation_coount_journalmatrix_citation_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_type', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RenameField(
            model_name='volume',
            old_name='close_year',
            new_name='year',
        ),
        migrations.RemoveField(
            model_name='journals',
            name='ISSM_ONLINE',
        ),
        migrations.RemoveField(
            model_name='journals',
            name='ISSM_PRINT',
        ),
        migrations.RemoveField(
            model_name='volume',
            name='open_year',
        ),
        migrations.AddField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('open', 'open'), ('close', 'close')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='journals',
            name='ISSN_ONLINE',
            field=models.IntegerField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='journals',
            name='ISSN_PRINT',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='journals',
            name='article_type',
        ),
        migrations.AddField(
            model_name='journals',
            name='article_type',
            field=models.ManyToManyField(blank=True, null=True, to='journal.ArticleType'),
        ),
    ]
