# Generated by Django 3.1 on 2022-04-22 08:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('journal', '0003_auto_20220422_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journals',
            name='ISSN_ONLINE',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='journals',
            name='ISSN_PRINT',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='journals',
            name='journal_author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscriber_author_journal', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='journals',
            name='journal_reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscriber_reviewer_journal', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='journals',
            name='journal_subscriber',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscriber_journal', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='journals',
            name='special_issue',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
