# Generated by Django 3.1 on 2022-04-22 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0004_auto_20220422_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journals',
            name='scope',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ScopeType',
        ),
    ]
