# Generated by Django 4.0.2 on 2022-04-05 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0004_pagenumber_alter_journals_issue_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journals',
            name='ISSN_ONLINE',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
