# Generated by Django 3.1 on 2022-04-22 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0005_auto_20220422_1434'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScopeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope_type', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='journals',
            name='scope',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='journal.scopetype'),
        ),
    ]
