# Generated by Django 3.2 on 2022-07-24 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0006_auto_20220619_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journals',
            name='frequency',
            field=models.CharField(choices=[('monthly', 'monthly'), ('bimonthly', 'bimonthly'), ('quaterly', 'quaterly'), ('half_yearly', 'half_yearly'), ('yearly', 'yearly')], default='monthly', max_length=100),
        ),
    ]
