# Generated by Django 3.1 on 2022-04-22 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0006_auto_20220422_1440'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journals',
            name='scope',
        ),
        migrations.AddField(
            model_name='journals',
            name='scope',
            field=models.ManyToManyField(blank=True, null=True, to='journal.ScopeType'),
        ),
    ]
