# Generated by Django 3.2.15 on 2022-09-05 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0007_alter_journals_frequency'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
    ]
