# Generated by Django 3.2 on 2022-05-03 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0008_auto_20220424_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journals',
            name='journal_id',
            field=models.SlugField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
