# Generated by Django 3.2 on 2022-05-03 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0009_alter_journals_journal_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journals',
            old_name='journal_id',
            new_name='journal_slug',
        ),
    ]
