# Generated by Django 3.2 on 2022-05-03 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0010_rename_journal_id_journals_journal_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='paper_id',
        ),
        migrations.AddField(
            model_name='article',
            name='paper_slug',
            field=models.SlugField(default=1, max_length=225),
            preserve_default=False,
        ),
    ]
