# Generated by Django 3.2 on 2022-05-03 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0011_auto_20220504_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='paper_slug',
            field=models.SlugField(max_length=200),
        ),
    ]
