# Generated by Django 3.2 on 2022-05-03 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0012_alter_article_paper_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='paper_slug',
        ),
        migrations.AddField(
            model_name='article',
            name='article_slug',
            field=models.SlugField(default=1, max_length=225),
            preserve_default=False,
        ),
    ]
