# Generated by Django 3.2 on 2022-05-08 13:59

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0013_auto_20220504_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journals',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
    ]
