# Generated by Django 3.2 on 2022-05-08 14:23

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0014_alter_journals_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='refrence',
            field=tinymce.models.HTMLField(default=1),
            preserve_default=False,
        ),
    ]
