# Generated by Django 3.2 on 2022-06-19 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Author', 'Author'), ('Editor', 'Editor'), ('Reviewer', 'Reviewer'), ('Both-ER', 'Both-ER'), ('Subscriber', 'Subscriber')], max_length=20),
        ),
    ]
