# Generated by Django 4.0.2 on 2022-03-29 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_contact_alter_user_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Author', 'Author'), ('Editor', 'Editor'), ('Reviewer', 'Reviewer'), ('Subscriber', 'Subscriber')], max_length=20),
        ),
    ]
