# Generated by Django 3.2.16 on 2022-11-02 18:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('editorial', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author_details',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='article_author_details', to=settings.AUTH_USER_MODEL),
        ),
    ]
