# Generated by Django 3.2.15 on 2022-09-11 08:55

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('journal', '0008_delete_article'),
        ('editorial', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='editor_details',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'Editor'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article_editor_details', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='article',
            name='author_details',
            field=models.OneToOneField(limit_choices_to={'role': 'Author'}, on_delete=django.db.models.deletion.CASCADE, related_name='article_author_details', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='article',
            name='citation',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='copyright_form',
            field=models.FileField(blank=True, null=True, upload_to='foo/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['doc', 'docx', 'pdf'])]),
        ),
        migrations.AlterField(
            model_name='article',
            name='date_of_acceptance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='date_of_published',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='date_of_submission',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='doi',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='download_count',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='issue',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='multiple_image_in',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='page_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article_page_number', to='journal.pagenumber'),
        ),
        migrations.AlterField(
            model_name='article',
            name='published_article',
            field=models.FileField(blank=True, null=True, upload_to='foo/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
        migrations.AlterField(
            model_name='article',
            name='published_html',
            field=models.FileField(blank=True, null=True, upload_to='foo/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['html'])]),
        ),
        migrations.AlterField(
            model_name='article',
            name='published_xml',
            field=models.FileField(blank=True, null=True, upload_to='foo/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['xml'])]),
        ),
        migrations.AlterField(
            model_name='article',
            name='reviewer_report',
            field=models.FileField(blank=True, null=True, upload_to='foo/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
        migrations.AlterField(
            model_name='article',
            name='supplementary_file',
            field=models.FileField(blank=True, null=True, upload_to='foo/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['doc', 'docx', 'zip'])]),
        ),
        migrations.AlterField(
            model_name='article',
            name='upload',
            field=models.FileField(blank=True, null=True, upload_to='foo/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['doc', 'docx', 'zip'])]),
        ),
        migrations.AlterField(
            model_name='article',
            name='view_count',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='volume',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
