# Generated by Django 3.2.15 on 2022-09-11 09:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('editorial', '0002_auto_20220911_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='ArticleActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_editor_approved', models.BooleanField(blank=True, default=False, null=True)),
                ('is_author_approved', models.BooleanField(blank=True, default=False, null=True)),
                ('created_at', models.BooleanField(blank=True, default=False, null=True)),
                ('updated_at', models.BooleanField(blank=True, default=False, null=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article', to='editorial.article')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
