# Generated by Django 3.2.16 on 2022-11-02 18:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('editorial', '0004_alter_articleactivity_commented_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author_details',
            field=models.OneToOneField(limit_choices_to={'role__name': 'Author'}, on_delete=django.db.models.deletion.CASCADE, related_name='article_author_details', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='article',
            name='editor_details',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__name': 'Editor'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article_editor_details', to=settings.AUTH_USER_MODEL),
        ),
    ]
