# Generated by Django 3.2.15 on 2022-09-11 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editorial', '0005_alter_articleactivity_article'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articleactivity',
            name='is_author_approved',
        ),
        migrations.AddField(
            model_name='articleactivity',
            name='is_admin_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='articleactivity',
            name='is_reviewer_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='articleactivity',
            name='is_editor_approved',
            field=models.BooleanField(default=False),
        ),
    ]
