# Generated by Django 3.2.15 on 2022-09-11 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('editorial', '0006_auto_20220911_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleactivity',
            name='article',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='article_activity', to='editorial.article'),
        ),
    ]
