# Generated by Django 3.2.15 on 2022-09-11 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('editorial', '0007_alter_articleactivity_article'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articleactivity',
            old_name='article',
            new_name='article_instance',
        ),
    ]
