# Generated by Django 3.2.15 on 2022-09-11 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('editorial', '0008_rename_article_articleactivity_article_instance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articleactivity',
            old_name='article_instance',
            new_name='article',
        ),
    ]
